site_name: Project Docs
site_url: https://RCG1412.github.io/Practice-D-A-C/
repo_url: https://github.com/RCG1412/Practice-D-A-C
theme:
  name: material
nav:
- Home: index.md
- Getting Started: "Getting Started.md"
- Quick Start: "Quick Start Guide.md"
- API Reference Guide:
  - "docs/API Reference Guide/GET.md"
  - "docs/API Reference Guide/POST.md"